apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opshub.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opshub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.mysql.enabled }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.auth.rootPassword | quote }}
  {{- else }}
  mysql-password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | quote }}
  {{- else }}
  redis-password: {{ .Values.externalRedis.password | quote }}
  {{- end }}
  jwt-secret: {{ .Values.server.jwtSecret | quote }}
